#!/bin/sh

# Define test work dir
WORKDIR=@PTEST_PATH@/tests/

# Run test
cd ${WORKDIR}

./testsuite -k unittest | sed -e '/[0-9]:/s/://' \
    -e '/ ok/s/^/PASS: /;/ FAILED/s/^/FAIL: /;/ skipped/s/^/SKIP: /' \
    -e '/ ok/s/ ok.*//;/ skipped/s/ skipped.*//;/ FAILED/s/ FAILED.*//'

